<?php

declare(strict_types=1);

/*
 * (c) Tim Bernhard
 */

namespace App\Service;

use App\Entity\Statement;
use App\Entity\Substance;
use Psr\Log\LoggerInterface;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\Process\Process;

/**
 * GhsLabelGenerator generates printable GHS lab bottle labels as LaTeX or compiled PDF
 * using the project's vector templates in GHS-labels/.
 *
 * @author timbernhard
 */
class GhsLabelGenerator
{
    private const array SYMBOL_FIGURE_MAP = [
        'GHS01' => 'figures/explos',
        'GHS02' => 'figures/flamme',
        'GHS03' => 'figures/rondflam',
        'GHS04' => 'figures/bottle',
        'GHS05' => 'figures/acid',
        'GHS06' => 'figures/skull',
        'GHS07' => 'figures/exclam',
        'GHS08' => 'figures/silhouete',
        'GHS09' => 'figures/pollu',
    ];

    public function __construct(
        #[Autowire(param: 'kernel.project_dir')]
        private readonly string $projectDir,
        private readonly LoggerInterface $logger
    ) {
    }

    /**
     * Generate LaTeX (.tex) source code for a substance's GHS label.
     */
    public function generateTex(
        Substance $substance,
        string $firm = 'Lab Supply - Chemical Inventory',
        string $contact = 'Emergency Tel: 145'
    ): string {
        $templatePath = $this->projectDir . '/GHS-labels/template-A4.tex';
        if (file_exists($templatePath)) {
            $template = (string) file_get_contents($templatePath);
        } else {
            $template = $this->getDefaultTemplate();
        }

        // 1. Substance Name
        $name = $substance->getName() ?? 'Unknown Chemical';
        $chemNameTex = '\huge ' . $this->escapeLatex($name);

        // 2. Signal Word
        $signalWord = strtoupper($substance->getSignalWord() ?? 'WARNING');
        $signalTex = $this->escapeLatex($signalWord);

        // 3. GHS Symbols (up to 4)
        $figurePaths = [];
        foreach ($substance->getSymbols() as $symbol) {
            $symName = strtoupper(trim((string) $symbol->getName()));
            if (isset(self::SYMBOL_FIGURE_MAP[$symName])) {
                $figurePaths[] = self::SYMBOL_FIGURE_MAP[$symName];
            }
        }
        $figurePaths = array_slice(array_unique($figurePaths), 0, 4);

        $firstSymbol = isset($figurePaths[0]) ? sprintf('\newcommand{\FirstSymbol}{%s}', $figurePaths[0]) : '';
        $secondSymbol = isset($figurePaths[1]) ? sprintf('\newcommand{\SecondSymbol}{%s}', $figurePaths[1]) : '';
        $thirdSymbol = isset($figurePaths[2]) ? sprintf('\newcommand{\ThirdSymbol}{%s}', $figurePaths[2]) : '';
        $fourthSymbol = isset($figurePaths[3]) ? sprintf('\newcommand{\FourthSymbol}{%s}', $figurePaths[3]) : '';

        // 4. Hazards (H-statements) & Precautions (P-statements)
        $hazardLines = [];
        $precautionLines = [];

        foreach ($substance->getStatements() as $statement) {
            $code = $this->escapeLatex((string) $statement->getName());
            $desc = $statement->getDescription() ? ': ' . $this->escapeLatex($statement->getDescription()) : '';
            $line = $code . $desc . '\\\\';

            if ($statement->getType() === Statement::TYPE_H || str_starts_with($code, 'H') || str_starts_with($code, 'EUH')) {
                $hazardLines[] = $line;
            } else {
                $precautionLines[] = $line;
            }
        }

        $hazardsTex = implode("\n", $hazardLines);
        $precautionsTex = implode("\n", $precautionLines);

        // 5. Additional info (CAS, Formula)
        $additionals = [];
        if ($substance->getCASNumber()) {
            $additionals[] = 'CAS: ' . $this->escapeLatex($substance->getCASNumber()) . '\\\\';
        }
        if ($substance->getFormula()) {
            $additionals[] = 'Formula: ' . $this->escapeLatex($substance->getFormula()) . '\\\\';
        }
        $additionalsTex = implode("\n", $additionals);

        // 6. Firm & Contact
        $firmTex = $this->escapeLatex($firm . ' -- ' . $contact);

        // Build output document by replacing variables in template or injecting definition block
        return <<<LATEX
% GHS Label generated by MSD Database for {$this->escapeLatex($name)}
\\newcommand{\\Chemname}{{$chemNameTex}}
\\newcommand{\\Signal}{{$signalTex}}
{$firstSymbol}
{$secondSymbol}
{$thirdSymbol}
{$fourthSymbol}
\\newcommand{\\txtsize}{\\small}
\\newcommand{\\Hazards}{%
{$hazardsTex}
}
\\newcommand{\\Precautions}{%
{$precautionsTex}
}
\\newcommand{\\Additionals}{%
{$additionalsTex}
}
\\newcommand{\\Firm}{{$firmTex}}
\\newcommand{\\filedate}{\\number\\year-\\number\\month-\\number\\day}

\\documentclass[a4paper]{article}
\\usepackage{times}
\\usepackage[utf8]{inputenc}
\\usepackage{ifthen}
\\usepackage{graphicx}
\\usepackage{labels}

\\LabelCols=2%
\\LabelRows=4%
\\LeftBorder=-10mm%
\\RightBorder=0mm%
\\TopBorder=1mm%
\\BottomBorder=0mm%
\\numberoflabels=8%

\\begin{document}
\\genericlabel{%
  \\raisebox{29mm}{\\parbox[t][65mm][t]{90mm}{
    \\textbf{\\Chemname}\\\\
    \\parbox[t][60mm][t]{15mm}{\\mbox{}\\\\
      \\ifthenelse{\\isundefined{\\FirstSymbol}}{}{%
        \\resizebox{14mm}{!}{\\includegraphics{\\FirstSymbol}}}
      \\ifthenelse{\\isundefined{\\SecondSymbol}}{}{%
        \\resizebox{14mm}{!}{\\includegraphics{\\SecondSymbol}}}
      \\ifthenelse{\\isundefined{\\ThirdSymbol}}{}{%
        \\resizebox{14mm}{!}{\\includegraphics{\\ThirdSymbol}}}
      \\ifthenelse{\\isundefined{\\FourthSymbol}}{}{%
        \\resizebox{14mm}{!}{\\includegraphics{\\FourthSymbol}}}
    }\\hspace{1pt}%
    \\parbox[t][61mm][t]{82mm}{\\txtsize
      \\textbf{\\normalsize\\Signal}\\\\[2pt]
      {\\Hazards}\\\\[2pt]
      {\\Precautions}\\\\[2pt]
      {\\Additionals}\\\\
      \\vfill
      \\rule[2pt]{82mm}{.5pt}\\\\
      \\tiny\\Firm\\hfill\\filedate
    }%
  }}%
}
\\end{document}
LATEX;
    }

    /**
     * Compile substance GHS label to PDF binary if pdflatex is installed.
     */
    public function generatePdf(Substance $substance): ?string
    {
        $tex = $this->generateTex($substance);
        $tempDir = sys_get_temp_dir() . '/ghs_label_' . uniqid('', true);
        mkdir($tempDir, 0777, true);

        try {
            $texFile = $tempDir . '/label.tex';
            file_put_contents($texFile, $tex);

            // Copy figures directory into temp dir so pdflatex can resolve \includegraphics{figures/...}
            $figuresDir = $this->projectDir . '/GHS-labels/figures';
            if (is_dir($figuresDir)) {
                mkdir($tempDir . '/figures', 0777, true);
                foreach (glob($figuresDir . '/*.pdf') ?: [] as $fig) {
                    copy($fig, $tempDir . '/figures/' . basename($fig));
                }
            }

            $process = new Process(['pdflatex', '-interaction=nonstopmode', 'label.tex'], $tempDir);
            $process->setTimeout(15);
            $process->run();

            $pdfFile = $tempDir . '/label.pdf';
            if (file_exists($pdfFile) && filesize($pdfFile) > 0) {
                return (string) file_get_contents($pdfFile);
            }

            $this->logger->warning('GHS Label pdflatex compilation returned no PDF output: ' . $process->getErrorOutput());
            return null;
        } catch (\Throwable $e) {
            $this->logger->warning('GHS Label PDF generation failed: ' . $e->getMessage());
            return null;
        } finally {
            $this->cleanupDir($tempDir);
        }
    }

    private function escapeLatex(string $text): string
    {
        $map = [
            '\\' => '\\textbackslash{}',
            '&' => '\\&',
            '%' => '\\%',
            '$' => '\\$',
            '#' => '\\#',
            '_' => '\\_',
            '{' => '\\{',
            '}' => '\\}',
            '~' => '\\textasciitilde{}',
            '^' => '\\textasciicircum{}',
        ];

        return strtr($text, $map);
    }

    private function cleanupDir(string $dir): void
    {
        if (!is_dir($dir)) {
            return;
        }
        foreach (scandir($dir) ?: [] as $file) {
            if ($file === '.' || $file === '..') {
                continue;
            }
            $path = $dir . '/' . $file;
            if (is_dir($path)) {
                $this->cleanupDir($path);
            } else {
                @unlink($path);
            }
        }
        @rmdir($dir);
    }

    private function getDefaultTemplate(): string
    {
        return '\documentclass[a4paper]{article}\begin{document}Label\end{document}';
    }
}
